### PR TITLE
docs(core): add codecov badge (#266)

### LINKED ISSUE #266: Add codecov badge to README.md

### PR DESCRIPTION
**Pull request by kacper-cyra**
Closes #266

### CODE REVIEW

**Comment by nowakprojects** [comment]
@kacper-cyra Do you know if it's possible to have badge per package (api / ui / panel etc.) ?

**Comment by kacper-cyra** [comment]
> 
> 
> @kacper-cyra Do you know if it's possible to have badge per package (api / ui / panel etc.) ?

I think it is. I will check it out.

**Review by lagdush — APPROVED** [review]

**Comment by kacper-cyra** [comment]
@nowakprojects We can do it but we can't distinguish them from each other, so we could make a table like this repo: https://github.com/ethereumjs/ethereumjs-monorepo

**Comment by nowakprojects** [comment]
> @nowakprojects We can do it but we can't distinguish them from each other, so we could make a table like this repo: https://github.com/ethereumjs/ethereumjs-monorepo

For me it'd be awesome! :) Could you try to do something similar like in the repo?

**Comment by kacper-cyra** [comment]
So I added "tests" category and badges but these badges shows only workflow action status, so if we would like to take full advantage of them we would need to run tests for each package in separate workflow.

**Comment by nowakprojects** [comment]
@KonradSzwarc c

> So I added "tests" category and badges but these badges shows only workflow action status, so if we would like to take full advantage of them we would need to run tests for each package in separate workflow.

Thanks @kacper-cyra ! :) 
Right now we can leave it, in the future we will probably introduce separated workflows.
@KonradSzwarc check out what do you think about it? I really like it :)

**Review by nowakprojects — APPROVED** [review]

**Pull request merged**
